# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # runs-on: ubuntu-22.04


    steps:
    - uses: actions/checkout@v4
    - run: 
        sudo apt install libfuse3-dev fuse3
        swift sdk install https://download.swift.org/swift-6.1-release/static-sdk/swift-6.1-RELEASE/swift-6.1-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz 


    - name: Build
      run: swift build -v
      working-directory: "fskit"
    # - name: Run tests
    #   run: swift test -v
