# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: ubuntu-22.04


    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt install meson ninja-build
        sudo snap install upx
    - name: Build libfuse
      working-directory: "fskit"
      run: |
        # sudo apt install libfuse3-dev fuse3

        # swift sdk install https://download.swift.org/swift-6.1.2-release/static-sdk/swift-6.1.2-RELEASE/swift-6.1.2-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz --checksum df0b40b9b582598e7e3d70c82ab503fd6fbfdff71fd17e7f1ab37115a0665b3b
        sudo apt install meson ninja-build
        ./build_libfuse.sh


    - name: Build
      # run: swift build --swift-sdk x86_64-swift-linux-musl
      run: swift build --static-swift-stdlib -c release
      working-directory: "fskit"
    - name: Compress
      run: upx -9 .build/release/Fuse

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: fskit
        path: .build/release/Fuse

    # - name: Run tests
    #   run: swift test -v